// Codex authoring check; portable rebuilds only require Python.
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {Workbook} from '@oai/artifact-tool';
const topic=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const matrix=JSON.parse(await fs.readFile(path.join(topic,'data/csv_matrix.json'),'utf8'));
const wb=Workbook.create();
const sheet=wb.worksheets.add('特徴的な文字形');
const range=sheet.getRange(`A1:V${matrix.length}`);
range.values=matrix;
const values=range.values;
if(JSON.stringify(values)!==JSON.stringify(matrix))throw new Error('Cell round trip mismatch');
const quote=v=>/[",\r\n]/.test(v)?'"'+v.replaceAll('"','""')+'"':v;
const csv='\uFEFF'+values.map(row=>row.map(quote).join(',')).join('\r\n')+'\r\n';
const file=path.join(topic,'output/ヨーロッパ周辺の特徴的な文字形.csv');
if(csv!==await fs.readFile(file,'utf8'))throw new Error('Portable CSV differs');
await fs.writeFile(file,csv);
const preview=wb.worksheets.add('確認');
preview.getRange('A1:D5').values=[['国','地域','言語','文字形'],...matrix.slice(1,5).map(r=>[r[1],r[2],r[3],r[5]])];
preview.getRange('A1:D5').format.font={name:'Noto Sans JP',size:12};
preview.getRange('A1:D5').format.columnWidth=30;
preview.getRange('A1:D5').format.rowHeight=46;
preview.getRange('A1:D1').format.fill='#173247';
preview.getRange('A1:D1').format.font.color='#FFFFFF';
const image=await wb.render({sheetName:'確認',range:'A1:D5',scale:1.5,format:'png'});
const cache=path.resolve(topic,'../../.cache/european-letterforms');
await fs.writeFile(path.join(cache,'csv-authoring-preview.png'),new Uint8Array(await image.arrayBuffer()));
console.log(`${values.length-1} rows authored; all ${matrix[0].length} columns round-trip exactly.`);
